# Generated by Django 5.2 on 2025-05-13 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Catspedia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(help_text="Description of the cat")),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("SPECIAL", "Special"),
                            ("RARE", "Rare"),
                            ("SUPER_RARE", "Super Rare"),
                            ("UBER_RARE", "Uber Rare"),
                            ("LEGEND_RARE", "Legend Rare"),
                        ],
                        default="NORMAL",
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="cats/")),
                (
                    "base_health",
                    models.IntegerField(
                        help_text="Base health points",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "base_attack",
                    models.IntegerField(
                        help_text="Base attack power",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "attack_range",
                    models.IntegerField(
                        default=140,
                        help_text="Attack range in pixels",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "attack_speed",
                    models.FloatField(
                        default=1.0,
                        help_text="Attack speed (attacks per second)",
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "movement_speed",
                    models.IntegerField(
                        default=10,
                        help_text="Movement speed",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "cost",
                    models.IntegerField(
                        default=75,
                        help_text="Cost to deploy",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "abilities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Abilities this cat has",
                        related_name="cats",
                        to="Catspedia.ability",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cat",
                "verbose_name_plural": "Cats",
                "ordering": ["rarity", "name"],
            },
        ),
    ]
